require "rubygems"
require "rake"

require "choctop"

ChocTop.new do |s|
  # Remote upload target
  s.host     = '2pii@imotifs.pearcomp.com'
  s.base_url   = "http://#{s.host}"
  s.remote_dir = '/home2/2pii/webapps/imotifs'

  # Custom DMG
  s.background_file = "Images/background.png"
  s.app_icon_position = [100, 110]
  s.applications_icon_position =  [420, 110]
  s.volume_icon = "Images/dmg128.png"

  #s.applications_icon = "icon.icns" # or "appicon.png"
  s.add_file("../quicklook/build/Debug/MotifQuickLook.qlgenerator",:position=>[100,400])
  s.add_file("./example.xms",:position=>[420,400])
  s.add_file("iMotifs Documentation.webloc", :position=>[235,280])
end
